### ISSUE TITLE
Would you please provide pretrained models for 'recon_g345', 'recon_g345_adv18', 'recon_g345_d0.2'?

### ISSUE THREAD

**Issue by jiangsutx** [paulu/deepfeatinterp#1]
I am doing some experiments on this project, the outputs are really amazing!

When I am trying to use some feed-forward network to accelerate, I found it already has that part in the code. [Here](https://github.com/paulu/deepfeatinterp/blob/master/deepmodels_torch.py#L21-L25)

```py
model_urls = {
    'recon_g345': 'recon-g345-d36b8ec0.pth',
    'recon_g345_adv18': 'recon-g345-adv18-6f7ababc.pth',
    'recon_g345_d0.2': 'recon-g345-d0.2-4239ba22.pth',
}
```
Where can I find these files please?
Thanks!

**Comment by paulu** [comment]
Sorry, those models are works-in-progress and they are not available.
