### ISSUE TITLE
Supplementary Material Broken File?

### ISSUE THREAD

**Issue by black-puppydog** [paulu/deepfeatinterp#2]
I've been trying to open the supplementary material from [the CVPR website](http://openaccess.thecvf.com/content_cvpr_2017/supplemental/Upchurch_Deep_Feature_Interpolation_2017_CVPR_supplemental.pdf) with a bunch of readers and failed.
Any chance you still have a working version? :)

By the way, there's no email contact on the paper or on your department website (that I could find) so sorry for spamming here.

**Comment by paulu** [comment]
Confirming that the one on the CVPR website doesn't load for me either.

This one works: [supplemental.](http://www.cs.cornell.edu/projects/dfi/dfi-supplemental.pdf) It is from the [project website](http://www.cs.cornell.edu/projects/dfi/) which also has links to our homepages with email addresses. Mine is paulu "at" cs.cornell.edu.

**Comment by black-puppydog** [comment]
Cool, thanks :)
