### ISSUE TITLE
Clarification: size of P/Q

### ISSUE THREAD

**Issue by black-puppydog** [paulu/deepfeatinterp#3]
In this part of `demo1.py`:
https://github.com/paulu/deepfeatinterp/blob/76b72e0a3b683a8cdeb13ed35b932680dc159ed1/demo1.py#L110-L112
I guess this is some left-over debugging code?
Because the next step is to select "up to K out of 1" which makes little sense to me.

**Comment by paulu** [comment]
It is not debugging code. make_manifolds() will create multiple pos/neg sets. In demo1, the images are processed one at a time, so we only need the first set.

**Comment by black-puppydog** [comment]
thanks, that helps. :)
