### ISSUE TITLE
server.py

### ISSUE THREAD

**Issue by geopapyrus** [paulu/deepfeatinterp#9]
Hi!

 Thanks for putting together such a detailed implementation.
 I am right now trying to rebuild your database.

 I'm almost done downloading all the images.

 As I look into the facemodel_server.py implementation, I noticed that it calls server.py.

 But I couldn't find server.py in the repo. Is it missing?

thak you!

**Comment by paulu** [comment]
It is inside the models/facemodel subdirectory.

https://github.com/paulu/deepfeatinterp/blob/master/models/facemodel/server.py

**Comment by geopapyrus** [comment]
Got it. Thanks!
